### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mroavi** [d0c-s4vage/lookatme.contrib.image_ueberzug#5]
I'm getting this error when trying to install this extension:

```zsh
❯ pip install lookatme.contrib.image_ueberzug
Defaulting to user installation because normal site-packages is not writeable
Collecting lookatme.contrib.image_ueberzug
  Using cached lookatme.contrib.image_ueberzug-1.1.0-py3-none-any.whl (3.7 kB)
  Using cached lookatme.contrib.image_ueberzug-1.0.1.tar.gz (3.1 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: lookatme<3.0.0,>=2.0.0 in ./.local/lib/python3.10/site-packages (from lookatme.contrib.image_ueberzug) (2.5.4)
  Using cached lookatme.contrib.image_ueberzug-1.0.0.tar.gz (1.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-65r9wda4/lookatme-contrib-image-ueberzug_9e8e5f3077d841858cb9b7fb437cebab/setup.py", line 11, in <module>
          with open(req_path, "r") as f:
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-65r9wda4/lookatme-contrib-image-ueberzug_9e8e5f3077d841858cb9b7fb437cebab/requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Any suggestions on how to fix this?

**Comment by mroavi** [comment]
Ohh no, **urwid-ueberzogen** does not exist in PyPI anymore:

![image](https://user-images.githubusercontent.com/19517248/205094174-39e8a01f-4ac4-42e2-9a24-f757928000cc.png)

Hmm.. the project got archived a few days ago: https://github.com/seebye/urwid-ueberzogen

**Comment by mroavi** [comment]
From https://github.com/seebye/ueberzug:

> seebye/ueberzug is not maintained
> I decided to archive all stuff related to this project
> due to people not being able to comprehend that
> publishing an open source project does not mean that a person is willing to spend their free time on the problems of others.
> Even after disabling issues and disabling pull requests you still get harassed and insulted at some third party sites.
> In my opinion this is really a rude thing to do to a person which was kind enough to share their free time project in case someone else has a use for it.
> I recommend you to stop using this project.

☹

**Comment by Gy-Hu** [comment]
> From https://github.com/seebye/ueberzug:
> 
> > seebye/ueberzug is not maintained
> > I decided to archive all stuff related to this project
> > due to people not being able to comprehend that
> > publishing an open source project does not mean that a person is willing to spend their free time on the problems of others.
> > Even after disabling issues and disabling pull requests you still get harassed and insulted at some third party sites.
> > In my opinion this is really a rude thing to do to a person which was kind enough to share their free time project in case someone else has a use for it.
> > I recommend you to stop using this project.
> 
> ☹

Hi, did you solve this? This seems the only one solution that can display image on terminal to do slideshow. Or have you found any alternatives to this?

**Comment by mroavi** [comment]
I turned to https://github.com/edluffy/hologram.nvim which is a Neovim plugin that uses the  Kitty Graphics Protocol to display images. Unfortunately, this plugin is not mature yet.

**Comment by Gy-Hu** [comment]
> I turned to https://github.com/edluffy/hologram.nvim which is a Neovim plugin that uses the Kitty Graphics Protocol to display images. Unfortunately, this plugin is not mature yet.

If you don't have the need for slideshow (only want to render the image on terminal within markdown), you may try https://github.com/swsnr/mdcat

**Comment by d0c-s4vage** [comment]
Wow @mroavi, I totally missed the email / notification about this issue. I'm working on a v3.0 of lookatme, with native image support being one of the next major features I'm going to be implementing.

This is the issue for it: https://github.com/d0c-s4vage/lookatme/issues/149

I want to support the three major terminal image protocols in lookatme: Sixel, IIS, and Kitty. It may end up being a separate library that I write to add that support that lookatme will then depend on (if something like that doesn't already exist).

If you want to try out one of the latest beta/release candidate  versions of v3.0 of lookatme, install it with:

```
pip install --upgrade --pre lookatme
```

To be clear, it doesn't have the native image support yet, but it does have:
* html support
* rendering to an html file
* generating documentation that looks like lookatme with a table of contents (lookatme's official documentation with move to this - https://d0c-s4vage.github.io/lookatme/)
* table column sorting (clickable headers)
* better styling capabilities
* progressive slide rendering (v2.X has this as well, but v3.0 supports progressive slides *anywhere*, not just between major block elements)
* visual ascii scrollbar for slides that are longer than the terminal height

This is the auto recorded gif of lookatme's tutorial for [v3.0.0rc4](https://github.com/d0c-s4vage/lookatme/releases/tag/v3.0.0rc4)
![](https://github.com/d0c-s4vage/lookatme/releases/download/v3.0.0rc4/tutorial.gif)
